# Generated by Django 4.2.6 on 2024-01-06 15:05

import apps.operation.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'روند بهبودی',
                'verbose_name_plural': 'روندهای بهبودی',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن آزمایش')),
                ('file', models.FileField(upload_to='files/tests/2024-01-06/', verbose_name='فایل آزمایش')),
                ('status', models.CharField(choices=[('answered', 'پاسخ داده'), ('await', 'بی پاسخ')], default='await', max_length=64, verbose_name='وضعیت')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آزمایش',
                'verbose_name_plural': 'آزمایش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SkinRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=apps.operation.utils.upload_routine_image, verbose_name='تصویر چهره کامل')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=apps.operation.utils.upload_routine_image, verbose_name='تصویر چهره راست')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=apps.operation.utils.upload_routine_image, verbose_name='تصویر چهره چپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_routines', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'روتین پوستی',
                'verbose_name_plural': 'روتین\u200cهای پوستی',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RecoveryProcessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('image', models.ImageField(upload_to=apps.operation.utils.upload_recovery_image, verbose_name='تصویر')),
                ('recovery_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operation.recoveryprocess', verbose_name='روند بهبودی')),
            ],
            options={
                'verbose_name': 'تصویر بهبودی',
                'verbose_name_plural': 'تصاویر بهبودی',
            },
        ),
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/counselings/2024-01-06/', verbose_name='فایل مشاوره')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشاوره',
                'verbose_name_plural': 'مشاوره\u200cها',
                'ordering': ('-id',),
            },
        ),
    ]
