# Generated by Django 4.2.6 on 2023-12-30 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Test text')),
                ('file', models.FileField(upload_to='files/tests/2023-12-30/', verbose_name='Test file')),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('await', 'Await')], default='await', max_length=64, verbose_name='وضعیت')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ('-created_at',),
            },
        ),
    ]
