# Generated by Django 4.2.6 on 2023-12-31 19:52

import apps.operation.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Recovery process',
                'verbose_name_plural': 'Recovery processes',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created_at',), 'verbose_name': 'آزمایش', 'verbose_name_plural': 'آزمایش\u200cها'},
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2023-12-31/', verbose_name='فایل آزمایش'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('answered', 'پاسخ داده'), ('await', 'بی پاسخ')], default='await', max_length=64, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن آزمایش'),
        ),
        migrations.CreateModel(
            name='RecoveryProcessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('image', models.ImageField(upload_to=apps.operation.utils.upload_recovery_image, verbose_name='تصویر')),
                ('recovery_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operation.recoveryprocess', verbose_name='Recovery process')),
            ],
            options={
                'verbose_name': 'Recovery image',
                'verbose_name_plural': 'Recovery images',
                'ordering': ('-id',),
            },
        ),
    ]
