# Generated by Django 4.2.6 on 2024-01-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_recoveryprocess_alter_test_options_alter_test_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoveryprocessimage',
            options={'verbose_name': 'Recovery image', 'verbose_name_plural': 'Recovery images'},
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2024-01-01/', verbose_name='فایل آزمایش'),
        ),
    ]
