# Generated by Django 4.2.6 on 2024-01-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_recoveryprocessimage_options_alter_test_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoveryprocess',
            options={'ordering': ('-id',), 'verbose_name': 'روند بهبودی', 'verbose_name_plural': 'روندهای بهبودی'},
        ),
        migrations.AlterModelOptions(
            name='recoveryprocessimage',
            options={'verbose_name': 'تصویر بهبودی', 'verbose_name_plural': 'تصاویر بهبودی'},
        ),
        migrations.AlterField(
            model_name='recoveryprocessimage',
            name='recovery_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operation.recoveryprocess', verbose_name='روند بهبودی'),
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2024-01-02/', verbose_name='فایل آزمایش'),
        ),
    ]
