# Generated by Django 4.2.6 on 2024-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_recoveryprocess_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2024-01-03/', verbose_name='فایل آزمایش'),
        ),
    ]
