# Generated by Django 4.2.6 on 2024-01-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_test_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2024-01-04/', verbose_name='فایل آزمایش'),
        ),
    ]
