# Generated by Django 4.2.6 on 2024-01-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_counseling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/counselings/2024-01-04/', verbose_name='Counseling file'),
        ),
    ]
