# Generated by Django 4.2.6 on 2024-01-05 01:13

import apps.operation.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_counseling_options_alter_counseling_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skinroutine',
            options={'ordering': ('-id',), 'verbose_name': 'روتین پوستی', 'verbose_name_plural': 'روتین\u200cهای پوستی'},
        ),
        migrations.AlterField(
            model_name='counseling',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/counselings/2024-01-05/', verbose_name='فایل مشاوره'),
        ),
        migrations.AlterField(
            model_name='skinroutine',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='skinroutine',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=apps.operation.utils.upload_routine_image, verbose_name='تصویر چهره کامل'),
        ),
        migrations.AlterField(
            model_name='skinroutine',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.operation.utils.upload_routine_image, verbose_name='تصویر چهره راست'),
        ),
        migrations.AlterField(
            model_name='skinroutine',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=apps.operation.utils.upload_routine_image, verbose_name='تصویر چهره چپ'),
        ),
        migrations.AlterField(
            model_name='skinroutine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2024-01-05/', verbose_name='فایل آزمایش'),
        ),
    ]
