# Generated by Django 4.2.6 on 2024-01-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_alter_skinroutine_options_alter_counseling_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/counselings/2024-01-06/', verbose_name='فایل مشاوره'),
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='files/tests/2024-01-06/', verbose_name='فایل آزمایش'),
        ),
    ]
