# Generated by Django 4.2.6 on 2024-01-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('defined', 'تعریف شده'), ('undefined', 'تعریف نشده'), ('edited', 'ویرایش شده')], default='undefined', max_length=64, verbose_name='وضعیت')),
                ('saturday', models.TextField(blank=True, null=True, verbose_name='برنامه شنبه')),
                ('sunday', models.TextField(blank=True, null=True, verbose_name='برنامه یکشنبه')),
                ('monday', models.TextField(blank=True, null=True, verbose_name='برنامه دوشنبه')),
                ('tuesday', models.TextField(blank=True, null=True, verbose_name='برنامه سه\u200cشنبه')),
                ('wednesday', models.TextField(blank=True, null=True, verbose_name='برنامه چهارشنبه')),
                ('thursday', models.TextField(blank=True, null=True, verbose_name='برنامه پنجشنبه')),
                ('friday', models.TextField(blank=True, null=True, verbose_name='برنامه جمعه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_programs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'برنامه ورزشی',
                'verbose_name_plural': 'برنامه\u200cهای ورزشی',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('defined', 'تعریف شده'), ('undefined', 'تعریف نشده'), ('edited', 'ویرایش شده')], default='undefined', max_length=64, verbose_name='وضعیت')),
                ('saturday', models.TextField(blank=True, null=True, verbose_name='برنامه شنبه')),
                ('sunday', models.TextField(blank=True, null=True, verbose_name='برنامه یکشنبه')),
                ('monday', models.TextField(blank=True, null=True, verbose_name='برنامه دوشنبه')),
                ('tuesday', models.TextField(blank=True, null=True, verbose_name='برنامه سه\u200cشنبه')),
                ('wednesday', models.TextField(blank=True, null=True, verbose_name='برنامه چهارشنبه')),
                ('thursday', models.TextField(blank=True, null=True, verbose_name='برنامه پنجشنبه')),
                ('friday', models.TextField(blank=True, null=True, verbose_name='برنامه جمعه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_programs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'برنامه تغذیه',
                'verbose_name_plural': 'برنامه\u200cهای تغذیه',
                'ordering': ('-id',),
            },
        ),
    ]
