# Generated by Django 4.2.6 on 2023-12-25 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartex', '0004_meeting_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_set_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
