# Generated by Django 4.2.6 on 2024-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartex', '0006_alter_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='device_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
