# Generated by Django 4.2.6 on 2024-01-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Id delivered'),
        ),
    ]
