# Generated by Django 4.2.6 on 2023-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorcategory',
            name='picture',
            field=models.ImageField(default='d', upload_to='images/services/operators/pictures/', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
