# Generated by Django 4.2.6 on 2024-01-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('-id',), 'verbose_name': 'اپراتور', 'verbose_name_plural': 'Operators'},
        ),
        migrations.AlterModelOptions(
            name='operatorcategory',
            options={'verbose_name': 'Operator category', 'verbose_name_plural': 'Operator categories'},
        ),
        migrations.AlterModelOptions(
            name='operatorreserve',
            options={'ordering': ('-id',), 'verbose_name': 'Operator reserve', 'verbose_name_plural': 'Operator reserves'},
        ),
        migrations.AlterModelOptions(
            name='operatorworksample',
            options={'verbose_name': 'Operator work sample', 'verbose_name_plural': 'Operator work samples'},
        ),
    ]
