# Generated by Django 4.2.6 on 2023-12-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_operatorcategory_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorcategory',
            name='picture',
        ),
        migrations.AddField(
            model_name='operator',
            name='picture',
            field=models.ImageField(default='test', upload_to='images/services/operators/pictures/', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
