# Generated by Django 4.2.6 on 2023-12-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_operatorcategory_picture_operator_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.operator', verbose_name='اپراتور')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
