# Generated by Django 4.2.6 on 2023-12-30 07:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_operatorreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorreserve',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9130001122', max_length=32, region=None, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
    ]
