# Generated by Django 4.2.6 on 2023-12-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Admin answer'),
        ),
    ]
