# Generated by Django 4.2.6 on 2023-12-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_ticket_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-id',), 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=64, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(verbose_name='متن تیکت'),
        ),
    ]
