# Generated by Django 4.2.6 on 2023-12-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=32, region=None, unique=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='نشانی الکترونیک')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('access_level', models.CharField(choices=[('user', 'کاربر'), ('admin', 'ادمین'), ('operator', 'اپراتور')], default='user', max_length=32, verbose_name='سطح دسترسی')),
                ('token', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='رمز مخفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('question1', models.CharField(default='بدون جواب', max_length=64, verbose_name='سوال اول')),
                ('question2', models.CharField(default='بدون جواب', max_length=64, verbose_name='سوال دوم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/user/profile/', verbose_name='تصویر')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='قد')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='وزن')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200c کاربران',
            },
        ),
    ]
