# Generated by Django 4.2.6 on 2024-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(choices=[('user', 'کاربر'), ('admin', 'ادمین'), ('operator', 'اپراتور'), ('diet_op', 'Diet operator'), ('workout_op', 'Workout operator')], max_length=64, verbose_name='Access title')),
            ],
            options={
                'verbose_name': 'Access',
                'verbose_name_plural': 'Accesses',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_level',
        ),
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(default='user', to='account.access', verbose_name='Accesses'),
        ),
    ]
