# Generated by Django 4.2.6 on 2024-01-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_access_remove_user_access_level_user_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'دسترسی', 'verbose_name_plural': 'دسترسی\u200cها'},
        ),
        migrations.AlterField(
            model_name='access',
            name='title',
            field=models.CharField(choices=[('user', 'کاربر'), ('admin', 'ادمین'), ('operator', 'اپراتور'), ('diet_op', 'اپراتور تغذیه'), ('workout_op', 'اپراتور ورزشی')], max_length=64, unique=True, verbose_name='عنوان دسترسی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(blank=True, default='user', to='account.access', verbose_name='دسترسی\u200cها'),
        ),
    ]
