# Generated by Django 4.2.6 on 2023-12-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
