# Generated by Django 4.2.6 on 2024-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_level_alter_access_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(blank=True, to='account.access', verbose_name='دسترسی\u200cها'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('basic', 'عادی'), ('vip', 'ویژه')], default='basic', max_length=32, verbose_name='سطح پروفایل'),
        ),
    ]
