# Generated by Django 4.2.6 on 2023-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='رمز مخفی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question1',
            field=models.CharField(default='بدون جواب', max_length=64, verbose_name='سوال اول'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question2',
            field=models.CharField(default='بدون جواب', max_length=64, verbose_name='سوال دوم'),
        ),
    ]
