# Generated by Django 4.2.6 on 2023-12-28 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kwargs',
            field=models.JSONField(blank=True, null=True, verbose_name='متغییرهای کلیدی'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_notify',
            field=models.BooleanField(default=True, verbose_name='ارسال اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان عنوان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='به کاربر'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MOBILE_VERIFICATION_CODE', 'کد تایید شماره موبایل')], max_length=128, verbose_name='نوع اعلان'),
        ),
    ]
