# Generated by Django 4.2.6 on 2023-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('title', models.CharField(default='No title', max_length=64, verbose_name='Title')),
                ('caption', models.TextField(blank=True, max_length=512, null=True, verbose_name='Caption')),
                ('image', models.ImageField(upload_to='images/story/2023-12-16/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ('-id',),
            },
        ),
    ]
