# Generated by Django 4.2.6 on 2023-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/post/2023-12-30/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2023-12-30/', verbose_name='تصویر'),
        ),
    ]
