# Generated by Django 4.2.6 on 2023-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-id',), 'verbose_name': 'استوری', 'verbose_name_plural': 'استوری\u200cها'},
        ),
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2023-12-16/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=64, verbose_name='عنوان'),
        ),
    ]
