# Generated by Django 4.2.6 on 2024-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/posts/2024-01-09/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2024-01-09/', verbose_name='تصویر'),
        ),
    ]
