# Generated by Django 4.2.6 on 2023-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_post_postlike_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Text'),
        ),
    ]
