# Generated by Django 4.2.6 on 2023-12-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_postcomment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-id',), 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'لایک پست', 'verbose_name_plural': 'لایک\u200cهای پست'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='public.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='public.post', verbose_name='پست'),
        ),
    ]
