# Generated by Django 4.2.6 on 2023-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_post_options_alter_postcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/post/2023-12-17/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=255, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2023-12-17/', verbose_name='تصویر'),
        ),
    ]
