# Generated by Django 4.2.6 on 2024-01-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_remove_post_image_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/posts/2024-01-02/', verbose_name='File'),
        ),
    ]
