# Generated by Django 4.2.6 on 2023-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_post_image_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/post/2023-12-21/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2023-12-21/', verbose_name='تصویر'),
        ),
    ]
