# Generated by Django 4.2.6 on 2024-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
        migrations.AddField(
            model_name='story',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/posts/2024-01-03/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2024-01-03/', verbose_name='تصویر'),
        ),
    ]
