# Generated by Django 4.2.6 on 2024-01-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_post_pinned_story_pinned_alter_post_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/posts/2024-01-04/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2024-01-04/', verbose_name='تصویر'),
        ),
    ]
