# Generated by Django 4.2.6 on 2024-01-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_post_file_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/posts/2024-01-05/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2024-01-05/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='story',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
    ]
