# Generated by Django 4.2.6 on 2023-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_alter_post_image_alter_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/post/2023-12-27/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2023-12-27/', verbose_name='تصویر'),
        ),
    ]
