# Generated by Django 4.2.6 on 2024-01-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_alter_post_file_alter_post_pinned_alter_story_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/posts/2024-01-06/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/story/2024-01-06/', verbose_name='تصویر'),
        ),
    ]
