# Generated by Django 4.2.6 on 2023-12-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_postcomment_is_active_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
